# Generated by Django 4.1 on 2022-09-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
