# Generated by Django 4.1 on 2022-09-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hang', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='modpass',
        ),
    ]
